import React, { useCallback, useEffect, useMemo, useState } from "react";
import { Archive, FolderPlus, Pencil, Plus, RotateCcw, X } from "lucide-react";
import { asList, getCategories, getGroups, saveCategory, saveGroup, setCategoryArchived, setGroupArchived } from "../services/budget";
import { Button, Card, EmptyState, ErrorBanner, Field, inputClass, LoadingState, PageHeader } from "../components/ui";

export default function CategoriesPage() {
  const [groups, setGroups] = useState([]);
  const [categories, setCategories] = useState([]);
  const [groupForm, setGroupForm] = useState(null);
  const [categoryForm, setCategoryForm] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); try { const [groupData, categoryData] = await Promise.all([getGroups(), getCategories()]); setGroups(asList(groupData)); setCategories(asList(categoryData)); setError(""); } catch (err) { setError(err.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const byGroup = useMemo(() => Object.fromEntries(groups.map((group) => [group.id, categories.filter((category) => category.group === group.id)])), [groups, categories]);

  const submitGroup = async (event) => { event.preventDefault(); try { await saveGroup({ name: groupForm.name, position: Number(groupForm.position) }, groupForm.id); setGroupForm(null); await load(); } catch (err) { setError(err.message); } };
  const submitCategory = async (event) => { event.preventDefault(); try { await saveCategory({ name: categoryForm.name, group: Number(categoryForm.group), position: Number(categoryForm.position) }, categoryForm.id); setCategoryForm(null); await load(); } catch (err) { setError(err.message); } };
  const archiveGroup = async (group) => { try { await setGroupArchived(group.id, !group.is_archived); await load(); } catch (err) { setError(err.message); } };
  const archiveCategory = async (category) => { try { await setCategoryArchived(category.id, !category.is_archived); await load(); } catch (err) { setError(err.message); } };

  return <div><PageHeader eyebrow="Sobres de dinero" title="Categorías" description="Agrupa tus prioridades y decide el orden en que aparecerán en el presupuesto." action={<div className="flex gap-2"><Button variant="secondary" onClick={() => setGroupForm({ name: "", position: groups.length })}><FolderPlus className="w-4 h-4" />Nuevo grupo</Button><Button disabled={!groups.some((g) => !g.is_archived)} onClick={() => setCategoryForm({ name: "", group: groups.find((g) => !g.is_archived)?.id || "", position: 0 })}><Plus className="w-4 h-4" />Nueva categoría</Button></div>} /><ErrorBanner message={error} />
    {groupForm && <Editor title={groupForm.id ? "Editar grupo" : "Nuevo grupo"} onClose={() => setGroupForm(null)} onSubmit={submitGroup}><Field label="Nombre"><input className={inputClass} value={groupForm.name} onChange={(e) => setGroupForm({ ...groupForm, name: e.target.value })} required /></Field><Field label="Orden"><input className={inputClass} type="number" min="0" value={groupForm.position} onChange={(e) => setGroupForm({ ...groupForm, position: e.target.value })} required /></Field></Editor>}
    {categoryForm && <Editor title={categoryForm.id ? "Editar categoría" : "Nueva categoría"} onClose={() => setCategoryForm(null)} onSubmit={submitCategory}><Field label="Nombre"><input className={inputClass} value={categoryForm.name} onChange={(e) => setCategoryForm({ ...categoryForm, name: e.target.value })} required /></Field><Field label="Grupo"><select className={inputClass} value={categoryForm.group} onChange={(e) => setCategoryForm({ ...categoryForm, group: e.target.value })}>{groups.filter((group) => !group.is_archived).map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></Field><Field label="Orden"><input className={inputClass} type="number" min="0" value={categoryForm.position} onChange={(e) => setCategoryForm({ ...categoryForm, position: e.target.value })} required /></Field></Editor>}
    {loading ? <LoadingState /> : !groups.length ? <Card><EmptyState title="Crea tu primer grupo" description="Por ejemplo: Necesidades, Estilo de vida o Ahorro." onAction={() => setGroupForm({ name: "", position: 0 })} actionLabel="Crear grupo" /></Card> : <div className="space-y-4">{groups.map((group) => <Card key={group.id} className={group.is_archived ? "opacity-60" : ""}><div className="px-5 py-4 border-b border-slate-800 flex items-center justify-between"><div><h2 className="font-bold">{group.name}</h2><p className="text-xs text-slate-500">Orden {group.position}{group.is_archived ? " · Archivado" : ""}</p></div><div className="flex gap-1"><Button variant="ghost" className="px-3" onClick={() => setGroupForm({ ...group })}><Pencil className="w-4 h-4" /></Button><Button variant={group.is_archived ? "secondary" : "danger"} className="px-3" onClick={() => archiveGroup(group)}>{group.is_archived ? <RotateCcw className="w-4 h-4" /> : <Archive className="w-4 h-4" />}</Button></div></div><div className="divide-y divide-slate-800/70">{!byGroup[group.id]?.length ? <p className="p-5 text-sm text-slate-500">Este grupo todavía no tiene categorías.</p> : byGroup[group.id].map((category) => <div key={category.id} className={`px-5 py-3.5 flex items-center justify-between ${category.is_archived ? "opacity-50" : ""}`}><div><p className="font-semibold text-sm">{category.name}</p><p className="text-xs text-slate-600">Orden {category.position}{category.is_archived ? " · Archivada" : ""}</p></div><div className="flex gap-1"><Button variant="ghost" className="px-3" onClick={() => setCategoryForm({ ...category })}><Pencil className="w-4 h-4" /></Button><Button variant={category.is_archived ? "secondary" : "danger"} className="px-3" onClick={() => archiveCategory(category)}>{category.is_archived ? <RotateCcw className="w-4 h-4" /> : <Archive className="w-4 h-4" />}</Button></div></div>)}</div></Card>)}</div>}
  </div>;
}

function Editor({ title, onClose, onSubmit, children }) { return <Card className="p-5 mb-6"><div className="flex items-center justify-between mb-5"><h2 className="font-bold">{title}</h2><button onClick={onClose} className="text-slate-500 hover:text-white"><X /></button></div><form onSubmit={onSubmit} className="grid md:grid-cols-[1fr_1fr_140px_auto] gap-4 items-end">{children}<Button type="submit">Guardar</Button></form></Card>; }

